In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [5]:
arr[2:6]

array([2, 3, 4, 5])

In [6]:
arr[0:3]

array([0, 1, 2])

In [7]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [9]:
arr[0:4] = 23

In [10]:
arr

array([23, 23, 23, 23,  4,  5,  6,  7,  8,  9])

In [11]:
arr = np.arange(0,10)

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
slice_arr = arr[3:8]

In [14]:
slice_arr

array([3, 4, 5, 6, 7])

In [15]:
slice_arr[:]

array([3, 4, 5, 6, 7])

In [16]:
slice_arr[:] = 66

In [17]:
slice_arr

array([66, 66, 66, 66, 66])

In [18]:
arr

array([ 0,  1,  2, 66, 66, 66, 66, 66,  8,  9])

In [19]:
arr_copy = arr.copy()

In [20]:
arr

array([ 0,  1,  2, 66, 66, 66, 66, 66,  8,  9])

In [21]:
arr_copy[:]

array([ 0,  1,  2, 66, 66, 66, 66, 66,  8,  9])

In [22]:
arr_copy[:] = 40

In [23]:
arr_copy

array([40, 40, 40, 40, 40, 40, 40, 40, 40, 40])

In [24]:
arr

array([ 0,  1,  2, 66, 66, 66, 66, 66,  8,  9])