In [1]:
import numpy as np

In [11]:
my_list = [1,2,3,4,5,6,7,8,9,0] 

In [14]:
arr = np.array(my_list)

In [15]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [16]:
my_matr = [[1,2,3],[4,5,6],[7,8,9]]

In [17]:
np.array(my_matr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.random.rand(6)

array([0.36603182, 0.77474716, 0.2258891 , 0.32318818, 0.2471431 ,
       0.89339647])

In [28]:
np.random.rand(6)

array([0.91988127, 0.19772322, 0.96722969, 0.41057373, 0.43911445,
       0.32397829])

In [30]:
np.random.rand(2,3)

array([[0.52027887, 0.26168835, 0.72281481],
       [0.1594584 , 0.28014409, 0.39407587]])

In [31]:
np.random.randint(40,60)

58

In [32]:
np.random.randint(40,60)

54

In [33]:
np.random.randint(1,50,5)

array([43, 34, 11, 27, 25])

In [34]:
arr1 = np.arange(10)

In [35]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
random_arr = np.random.randint(0,20,5)

In [37]:
random_arr

array([13,  2, 14, 13, 12])

In [38]:
arr1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
random_arr

array([13,  2, 14, 13, 12])

In [40]:
random_arr.max()

14

In [41]:
random_arr.min()

2

In [42]:
random_arr.argmax()

2

In [43]:
random_arr.argmin()

1

In [47]:
arr1 = arr1.reshape(5,2)

In [48]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
arr1.shape

(5, 2)

In [51]:
arr.dtype

dtype('int32')

In [52]:
arr1.dtype

dtype('int32')

In [53]:
from numpy.random import randint

In [54]:
randint(1,50)

10