In [1]:
import numpy as np

In [3]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr_2d[1]

array([4, 5, 6])

In [6]:
arr_2d[2][1]

8

In [7]:
arr_2d[2,1]

8

In [8]:
arr_2d[:1,0:]

array([[1, 2, 3]])

In [9]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [10]:
arr = np.arange(0,10)

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr > 7

array([False, False, False, False, False, False, False, False,  True,
        True])

In [13]:
bool_arr = arr > 4

In [14]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [15]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [17]:
arr[arr > 4]

array([5, 6, 7, 8, 9])

In [18]:
arr[arr < 7]

array([0, 1, 2, 3, 4, 5, 6])

In [19]:
arr_2d =np.arange(25).reshape(5,5)

In [20]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
arr_2d[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
arr_2d[2:1]

array([], shape=(0, 5), dtype=int32)